### PR TITLE
Node14 upgrade and browser test fixes

### PR DESCRIPTION
**Pull request by terovirtanen**
## Description

- fix browser tests
- node14 upgrade [KK-1008](https://helsinkisolutionoffice.atlassian.net/browse/KK-1008)
- remove github ci and review workflows [DEVOPS-522](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-522)

## Screenshots

[KK-1008]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVOPS-522]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr232.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr232.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr232.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr232.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr232.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr232.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr232.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr232.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr232.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr232.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr232.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr232.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr232.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr232.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr232.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr232.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr232.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr232.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr232.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr232.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr232.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr232.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr232.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr232.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr232.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-admin-pr232.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr232.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-admin-pr232.dev.hel.ninja :laughing::tada::tada::tada:

**Review by nikomakela — APPROVED** [review]

**Pull request merged**
