### PR TITLE
Cleaning related tot data provider and Child component

### PR DESCRIPTION
**Pull request by nikomakela**
KK-1049. 

- The Child component should not get any props as an argument
- Use some generics to clean the dataprovider.

The actual fix to this pagination issue should be included in the API change https://github.com/City-of-Helsinki/kukkuu/pull/332.

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr249.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr249.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by nikomakela** [comment]
The Browser tests fails because the login method is no longer available

**Review by karisal-anders — APPROVED** [review]

**Pull request merged**
