### PR TITLE
feat: idle user logout in 60mins

### PR DESCRIPTION
**Pull request by melniiv**
## Context

[KK-1218](https://helsinkisolutionoffice.atlassian.net/browse/KK-1218)

## Screenshots

[KK-1218]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr291.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr291.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr291.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-admin-pr291.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr291.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-admin-pr291.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr291.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-admin-pr291.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr291.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-admin-pr291.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr291.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-admin-pr291.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr291.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-admin-pr291.dev.hel.ninja :laughing::tada::tada::tada:

**Review by karisal-anders — APPROVED** [review]
The magic numbers could be a bit more documented / commented about like previously in https://github.com/City-of-Helsinki/kukkuu-ui/pull/591

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr291.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
