### PR TITLE
Use test jwt for browser tests

### PR DESCRIPTION
**Pull request by nikomakela**
KK-1168 KK-1203.

ref. KK-1168, KK-1195 and KK-1194.
ref. https://github.com/City-of-Helsinki/kukkuu-ui/pull/577.

Fix the browser tests, since they have been failing after we lost an old
authentication service that was specially created for the browser test
purposes. Especially now when we have been moving (and have actually
moved already) towards the Helsinki-Profile and it's Keycloak service,
we needed another approach to authenticate our browser test user.

The OIDC client and login provider are heavily trusting in that the
profile can be read from the session storage. This set of changes tries
to mock and mimic that so that the acutaly Keycloak won't be used at all
and a symmetrically signed test JWT is used instead.

1. Mock out the Keycloak authorization by mocking data to session
storage.
2. Use a symmetrically signed test JWT for Kukkuu API requests.

Depends on City-of-Helsinki/kukkuu#391. Also the pipeline configuration
needs to provide the new browser testing configurations, e.g. the shared
secret.

### CODE REVIEW

**Comment by nikomakela** [comment]
Currently in draft mode. Still to do:

- [ ] Provide documentation to setup the testing environment (locally).
- [ ] Configure the CI pipelines
- [ ] Merge the API changes, so the CI pipeline for this starts working

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr275.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr275.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-admin-pr275.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
