### PR TITLE
Upgrade Node 20 and all the dependencies

### PR DESCRIPTION
**Pull request by nikomakela**
KK-1017.
1. Start using Node 20
2. Upgrade all the deps with `yarn-upgrade-all`.
3. Migrate everything told in the React-Admin migration guide: https://marmelab.com/react-admin/Upgrade.html
4. Migrate everything told in the Material UI upgrade guide: https://mui.com/material-ui/migration/migration-v4/
5. Refactor some forms by merging the edit and create forms together
6. Fix the broken implementations after migration process

----

Biggest changes:

The React-Admin has started using 
1. The React-Router v6
2. React-hook-forms
3. React-query
4. Material UI v5

The props injection inside the React-admin app has been replaced with React-Context. All the record and resource props and all the views properties are replaced with context-hooks.

The React-Router v6 is a huge change, but the React-admin has done most of the migration related to that. This upgrade was huge in other Kuva's React-apps, but not in this.

Earlier the React-admin used the Redux to store the global state of all the inputs and fields. Now the Redux is removed and the fields are registered and handled with the React-hook-forms: https://react-hook-form.com/. This change is a huge one and most of the problems were related to this. The biggest issue was the data model that did not fit well with the React-admin-Material UI-React-hook-form implementation. The structure was forced to be simpler than what the Kukkuu API offers and the translations are handled differently. The actual problem was, that the form was showing only the values which were initialised to the form fields in the first tab rendered or in some cases, that when the tab was changed, the other tabs values were cleared from the context. *THE FORMS SHOULD BE CRITICALLY TESTED!* The fix to this is a bit sketchy now -- the React-Admin Translatable cannot be used, but there is now a custom implementation that works a lot similarly. The custom implementation relies on react-component keys and the whole implementation should already be wrapped with a react-hook-form formProvider.

The forms and views are much simpler now when the hooks are used under the hood.

Material UI v5 is also a huge change, but the visible elements should look quite the same in the React-admin as they were looking earlier. The components and styles comes from a differently named package (material-ui vs mui) and styles and themes are applied a bit differently, but these issues were easy to fix after the migration guide was followed carefully.

### CODE REVIEW

**Comment by nikomakela** [comment]
The tests should still be fixed

- [ ] Fix the unit tests

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-local.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Review by melniiv — APPROVED** [review]

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr241.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr241.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr241.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr241.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr241.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr241.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr241.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr241.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr241.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr241.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-admin-pr241.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-admin-pr241.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
