### PR TITLE
Add Lippupiste ticket system

### PR DESCRIPTION
**Pull request by nikomakela**
KK-1004. Added Lippupiste integration next oto Ticketmaster.

image

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr234.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-admin-pr234.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-ADMIN branch is deployed to platta: https://kukkuu-admin-pr234.dev.hel.ninja** :rocket::rocket::rocket:

**Review by karisal-anders — APPROVED** [review]
If you want to completely get rid of the `.kuva` environments and URLs there's also `https://tunnistamo.test.hel.ninja` which could probably replace `https://tunnistamo.test.kuva.hel.ninja`, at least https://tunnistamo.test.hel.ninja/.well-known/openid-configuration gives a valid response.
And
> - https://kukkuu-admin.test.kuva.hel.ninja/ (Deprecated KuVa environment)

could be removed from README.md.

**Comment by nikomakela** [comment]
> If you want to completely get rid of the .kuva environments and URLs there's also https://tunnistamo.test.hel.ninja which could probably replace https://tunnistamo.test.kuva.hel.ninja, at least https://tunnistamo.test.hel.ninja/.well-known/openid-configuration gives a valid response.
And
https://kukkuu-admin.test.kuva.hel.ninja/ (Deprecated KuVa environment)
could be removed from README.md.

Lets say that I would like to, but that would mean reconfiguring the public UI and the API also. Lets do that in a new task!

**Pull request merged**
